enum Status {
    SUBMITTED
    SELECTED
    REJECTED
    WAITING
}

type Conference {
    name: String!
    start_date: Date!
    end_date: Date
    venue: String!
    address: String!
    country: String!
    email: String!
    web: String!
    submissions: [Submission!] @relation
    committee: [User!]! @relation(name: "Committee")
}

type Review {
    submission: Submission!
    reviewer: User!
    score: Int!
    public: String
    private: String
}

type Submission {
    conference: Conference!
    accepted: Boolean!
    title: String!
    presenter: User!
    abstract: String!
    authors: [User!]! @relation(name: "Author")
    reviews: [Review!] @relation
    state: Status!
}

type User {
    committees: [Conference!] @relation(name: "Committee")
    submissions: [Submission!] @relation(name: "Author")
    first_name: String!
    last_name: String!
    email: String!
}
