enum Status {
    SUBMITTED
    SELECTED
    REJECTED
    WAITING
}

type Conference {
    name: String!
    short_name: String!
    start_date: Date!
    end_date: Date
    venue: String!
    address: String!
    country: String!
    email: String!
    web: String!
    reviewers: [Reviewer!]! @relation
    submissions: [Submission!] @relation
}

type Review {
    reviewer: Reviewer!
    submission: Submission!
    score: Int!
    public: String
    private: String
}

type Reviewer {
    conference: Conference!
    reviewer: User!
    reviews: [Review!] @relation
}

type Submission {
    conference: Conference!
    accepted: Boolean!
    title: String!
    abstract: String!
    authors: [User!]! @relation(name: "Author")
    reviews: [Review!] @relation
    status: Status!
}

type User {
    committees: [Reviewer!] @relation
    submissions: [Submission!] @relation(name: "Author")
    first_name: String!
    last_name: String!
    email: String!
}

type Query {
    allConferences: [Conference]
    allSubmissions: [Submission]
    allUsers: [User]
    conferenceByShortName(short_name: String): Conference
}